version: '3.4'

services:
    apigateway:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:5001;http://+:6001
        ports:
          - "25001:5001"
          - "26001:6001"
        volumes:
          - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
          - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    login:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development

    searchsettings:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development

    urlshortener:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development

    scheduller:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development

    engine:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development

    telegram:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
        ports:
        - "2443:443"
        - "26004:6004"
